/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
}

//
// Function: itemClicked()
// Called when an item from the items list is selected to navigate to the detail view
//
function itemClicked(event)
{
    var list = document.getElementById("list").object;
    var browser = document.getElementById('browser').object;
    var selectedObjects = list.selectedObjects();
    
    if (selectedObjects && (1 == selectedObjects.length)){
        // The Browser's goForward method is used to make the browser push down to a new level.
        // Going back to previous levels is handled automatically.
        browser.goForward(document.getElementById('detailLevel'), selectedObjects[0].valueForKey("name"));
    }    
}

//
// Function: itemDescription()
// This method is a value transformer that returns the appropriate description of the selected item in the list
//
itemDescription = Class.create(DC.ValueTransformer,{
	transformedValue: function(value){
        return "The scenery in " + value + " is amazing this time of year!";        
	}
});
